version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api_server.py:/app/api_server.py
      - ./update_urls.py:/app/update_urls.py
      - ./.env:/app/.env
    environment:
      - PORT=8000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
    restart: unless-stopped
    
  frontend:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm start"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped 